INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Regina','Sarampo',1,null,'-','2022-05-06');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Regina','Rubéola',1,null,'-','2022-05-03');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Regina','Tétano',1,null,'-','2022-04-28');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Regina','Covid',1,null,'Pfizer','2022-04-25');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Regina','Covid',2,null,'Corona vírus','2022-04-23');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Regina','Covid',null,1,'Astrazeneca','2022-04-19');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Regina','Febre amarela',1,null,'-','2022-04-19');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Regina','Gripe',1,null,'-','2022-04-18');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Regina','Paralisia infantil',1,null,'-','2022-04-17');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Regina','Hepatite A',1,null,'-','2022-04-12');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Robson','Sarampo',1,null,'-','2022-05-06');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Robson','Rubéola',1,null,'-','2022-05-03');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Robson','Tétano',1,null,'-','2022-04-28');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Robson','Covid',1,null,'Pfizer','2022-04-25');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Robson','Covid',2,null,'Corona vírus','2022-04-23');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Robson','Covid',null,1,'Astrazeneca','2022-04-19');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Robson','Febre amarela',1,null,'-','2022-04-19');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Robson','Gripe',1,null,'-','2022-04-18');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Robson','Paralisia infantil',1,null,'-','2022-04-17');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Robson','Hepatite A',1,null,'-','2022-04-12');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Yana','Sarampo',1,null,'-','2022-05-06');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Yana','Rubéola',1,null,'-','2022-05-03');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Yana','Tétano',1,null,'-','2022-04-28');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Yana','Covid',1,null,'Pfizer','2022-04-25');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Yana','Covid',2,null,'Corona vírus','2022-04-23');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Yana','Covid',null,1,'Astrazeneca','2022-04-19');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Yana','Febre amarela',1,null,'-','2022-04-19');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Yana','Gripe',1,null,'-','2022-04-18');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Yana','Paralisia infantil',1,null,'-','2022-04-17');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Yana','Hepatite A',1,null,'-','2022-04-12');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Marcos','Sarampo',1,null,'-','2022-05-06');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Marcos','Rubéola',1,null,'-','2022-05-03');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Marcos','Tétano',1,null,'-','2022-04-28');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Marcos','Covid',1,null,'Pfizer','2022-04-25');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Marcos','Covid',2,null,'Corona vírus','2022-04-23');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Marcos','Covid',null,1,'Astrazeneca','2022-04-19');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Marcos','Febre amarela',1,null,'-','2022-04-19');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Marcos','Gripe',1,null,'-','2022-04-18');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Marcos','Paralisia infantil',1,null,'-','2022-04-17');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Luiz','Hepatite A',1,null,'-','2022-04-12');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Luiz','Sarampo',1,null,'-','2022-05-06');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Luiz','Rubéola',1,null,'-','2022-05-03');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Luiz','Tétano',1,null,'-','2022-04-28');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Luiz','Covid',1,null,'Pfizer','2022-04-25');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Luiz','Covid',2,null,'Corona vírus','2022-04-23');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Luiz','Covid',null,1,'Astrazeneca','2022-04-19');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Luiz','Febre amarela',1,null,'-','2022-04-19');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Luiz','Gripe',1,null,'-','2022-04-18');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Luiz','Paralisia infantil',1,null,'-','2022-04-17');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Luiz','Hepatite A',1,null,'-','2022-04-12');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Jerlan','Sarampo',1,null,'-','2022-05-06');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Jerlan','Rubéola',1,null,'-','2022-05-03');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Jerlan','Tétano',1,null,'-','2022-04-28');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Jerlan','Covid',1,null,'Pfizer','2022-04-25');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Jerlan','Covid',2,null,'Corona vírus','2022-04-23');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Jerlan','Covid',null,1,'Astrazeneca','2022-04-19');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Jerlan','Febre amarela',1,null,'-','2022-04-19');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Jerlan','Gripe',1,null,'-','2022-04-18');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Jerlan','Paralisia infantil',1,null,'-','2022-04-17');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Jerlan','Hepatite A',1,null,'-','2022-04-12');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Raphael','Sarampo',1,null,'-','2022-05-06');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Raphael','Rubéola',1,null,'-','2022-05-03');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Raphael','Tétano',1,null,'-','2022-04-28');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Raphael','Covid',1,null,'Pfizer','2022-04-25');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Raphael','Covid',2,null,'Corona vírus','2022-04-23');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Raphael','Covid',null,1,'Astrazeneca','2022-04-19');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Raphael','Febre amarela',1,null,'-','2022-04-19');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Raphael','Gripe',1,null,'-','2022-04-18');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Raphael','Paralisia infantil',1,null,'-','2022-04-17');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Raphael','Hepatite A',1,null,'-','2022-04-12');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Márcio','Sarampo',1,null,'-','2022-05-06');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Márcio','Rubéola',1,null,'-','2022-05-03');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Márcio','Tétano',1,null,'-','2022-04-28');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Márcio','Covid',1,null,'Pfizer','2022-04-25');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Márcio','Covid',2,null,'Corona vírus','2022-04-23');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Márcio','Covid',null,1,'Astrazeneca','2022-04-19');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Márcio','Febre amarela',1,null,'-','2022-04-19');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Márcio','Gripe',1,null,'-','2022-04-18');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Márcio','Paralisia infantil',1,null,'-','2022-04-17');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('Márcio','Hepatite A',1,null,'-','2022-04-12');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('José','Sarampo',1,null,'-','2022-05-06');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('José','Rubéola',1,null,'-','2022-05-03');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('José','Tétano',1,null,'-','2022-04-28');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('José','Covid',1,null,'Pfizer','2022-04-25');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('José','Covid',2,null,'Corona vírus','2022-04-23');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('José','Covid',null,1,'Astrazeneca','2022-04-19');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('José','Febre amarela',1,null,'-','2022-04-19');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('José','Gripe',1,null,'-','2022-04-18');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('José','Paralisia infantil',1,null,'-','2022-04-17');
INSERT INTO tb_vacinas(name,vaccine_name,dose,complement,note,date) VALUES ('José','Hepatite A',1,null,'-','2022-04-12');
